name: Commit Stage
on: 
  push:
  workflow_dispatch:

env:
  BACKEND_DIR: ${{ github.workspace }}/services/agendo-backend/
  FRONTEND_DIR: ${{ github.workspace }}/agendo-ui/
  SECURITY_JWT_SECRET_KEY: 0d0a74917823f343407c8f00a1d37044fcc237a341032bc07dd65abf22323c83 # Secret key is ONLY used for this test job

jobs:
    build-and-test-backend:
        name: Build and test the backend
        runs-on: ubuntu-22.04
        permissions:
            contents: read
            security-events: write
        steps:
          - name: Checkout source code
            uses: actions/checkout@v4
          - name: Setup Java JDK
            uses: actions/setup-java@v4.6.0 
            with:
                distribution: temurin
                java-version: 21
                cache: maven
          - name: Code vulnerability scanning
            uses: anchore/scan-action@v6.0.0
            id: scan
            with:
                path: "${{ env.BACKEND_DIR }}"
                fail-build: true
                severity-cutoff: high
          - name: Upload vulnerability report
            uses: github/codeql-action/upload-sarif@v3
            if: success() || failure()
            with:
                sarif_file: ${{ steps.scan.outputs.sarif }}
          - name: Build, unit tests and integration tests
            run: |
                cd ${{ env.BACKEND_DIR }}
                chmod +x mvnw
                ./mvnw install

    build-frontend:
        name: Build the frontend
        runs-on: ubuntu-22.04
        permissions:
            contents: read
            security-events: write
        steps:
          - name: Checkout source code
            uses: actions/checkout@v4
          - name: Setup Node.js environment
            uses: actions/setup-node@v4.1.0
            with:
              node-version: 18
          - name: Code vulnerability scanning
            uses: anchore/scan-action@v6.0.0
            id: scan
            with:
                path: "${{ env.FRONTEND_DIR }}"
                fail-build: true
                severity-cutoff: high
          - name: Upload vulnerability report
            uses: github/codeql-action/upload-sarif@v3
            if: success() || failure()
            with:
                sarif_file: ${{ steps.scan.outputs.sarif }}
          - name: Build the frontend
            run: |
                cd ${{ env.FRONTEND_DIR }}
                npm ci
                npm build